// Generated by `npm run code`. The palette is the brand's, the turn is the episode's;
// editing either here would put this demo out of step with the reel it came from.
export { scene } from './fibonacci-sphere.js';

/** One turn of the loop, in milliseconds. The reel runs two of them at 60fps. */
export const CYCLE_MS = 10000;

export const PALETTE = {
  rest: '#5A6070',
  lead: '#0A84FF',
  /** r, g, b, a — composed into gradient stops in main.js. */
  glow: [10, 132, 255, 0.35],
};
